name: Main Pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  publish:
    name: Deploy Production
    needs: [tests]
    environment: 
      name: Production
      url: https://tawanb.dev
    runs-on: ubuntu-latest
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy Production
        run: vercel --prod --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
