name: Pull Request CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml
  deploy:
    name: Deploy Beta
    runs-on: ubuntu-latest
    needs: [tests]
    environment: Beta
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: check token
        run: echo "Token=${{ secrets.VERCEL_ACCESS_TOKEN }}..."
      - name: Deploy Beta
        id: deploy
        run: echo "url=$(vercel --token=${{ secrets.VERCEL_ACCESS_TOKEN }})" >> $GITHUB_OUTPUT
      - name: Notify update in PR
        uses: thollander/actions-comment-pull-request@v1
        if: success()
        with:
          message: |
            New beta version for this Pull Request has been released
            Service URL: ${{ steps.deploy.outputs.url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
